name: CD Pipeline

on:
  repository_dispatch:
    types: [ci-success]

jobs:
  build_docker_image_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Backend Docker image
        working-directory: ./backend
        run: |
          mvn clean package
          docker build -t richardolat/banking-app-backend:latest .
          docker push richardolat/banking-app-backend:latest
      - name: Build and push Frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t richardolat/banking-app-frontend:latest .
          docker push richardolat/banking-app-frontend:latest

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_docker_image_and_push
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull richardolat/banking-app-backend:latest
            docker pull richardolat/banking-app-frontend:latest
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 8080:8080 --name backend richardolat/banking-app-backend:latest
            docker run -d -p 3000:3000 --name frontend richardolat/banking-app-frontend:latest