name: CD Pipeline

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
        - staging
        - production
      skip-tests:
        description: 'Skip tests?'
        required: false
        default: 'false'
        type: boolean

# Added permissions block at workflow l
permissions:
  contents: write
  actions: write
  id-token: write  # Needed for AWS/GCP auth if you add it later

jobs:
  deploy_to_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Verify manual inputs
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Skip tests: ${{ github.event.inputs.skip-tests }}"
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying to ${{ github.event.inputs.environment || 'production' }} environment"
            docker pull richardolat/banking-app-backend:${{ github.run_id }}
            docker pull richardolat/banking-app-frontend:${{ github.run_id }}
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 8080:8080 --name backend richardolat/banking-app-backend:${{ github.run_id }}
            docker run -d -p 3000:3000 --name frontend richardolat/banking-app-frontend:${{ github.run_id }}
