name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Required parameter
          java-version: '17'
          cache: 'maven'  # Added caching for faster builds
          
      - name: Compile Backend
        working-directory: ./backend
        run: mvn -B clean compile  # -B for batch mode

  security-check:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Run security check
        working-directory: ./backend
        run: mvn -B verify

  test:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Run tests
        working-directory: ./backend
        run: mvn -B test

  trigger_cd:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger CD Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: ci-success
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'