name: CI Pipeline

on:
  push:
    branches:
      - main

# Added permissions block at workflow level
permissions:
  contents: write
  actions: write
  packages: write  # Needed for Docker pushes

jobs:
  build_docker_image_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Backend Docker image
        working-directory: ./backend
        run: |
          mvn clean package
          docker build -t richardolat/banking-app-backend:${{ github.run_id }} .
          docker build -t richardolat/banking-app-backend:latest .
          docker push richardolat/banking-app-backend:${{ github.run_id }}
          docker push richardolat/banking-app-backend:latest
          
      - name: Build and push Frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t richardolat/banking-app-frontend:${{ github.run_id }} .
          docker build -t richardolat/banking-app-frontend:latest .
          docker push richardolat/banking-app-frontend:${{ github.run_id }}
          docker push richardolat/banking-app-frontend:latest